name: Build and Push Images

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build backend
        run: |
          docker build -t ghcr.io/tjdus/unu-backend:latest ./backend

      - name: Push backend
        run: |
          docker push ghcr.io/tjdus/unu-backend:latest

      - name: Build frontend
        run: |
          docker build -t ghcr.io/tjdus/unu-frontend:latest ./frontend

      - name: Push frontend
        run: |
          docker push ghcr.io/tjdus/unu-frontend:latest
